### ISSUE TITLE
Examples of how to use the CustomerService

### ISSUE THREAD

**Issue by finbarrmccarthy** [zf-fr/zfr-cash#2]
Hello, I was wondering if you could help with an example of how to use the CustomerService. I am stuck with implementing ZfrCash\Repository\CustomerRepositoryInterface.

in my customer controller I have;
    use ZfrCash\Service\CustomerService;
    ...
    $em = $this->getEntityManager();
    $customer = new CustomerService($em,$customerRepository,$stripeClient);

The question is how do I use $customerRepository ??

Thank you.

**Comment by bakura10** [comment]
Hi,

ZfrCash is not ready yet, especially because DoctrineORMModule does not yet support some features of Doctrine 2.5 that are needed for this to work. But for the CustomerRepositoryInterface, you must set a custom repository for your entity that implements CustomerInterface:

``` php
/**
 * @ORM\Entity(repositoryClass="User\Repository\UserRepository")
 */
class User implements CustomerInterface
{
}
```

Then, create your repository (it must extends EntityRepository):

``` php
class UserRepository extends EntityRepository implements CustomerRepositoryInterface
{
   // ....
}
```

**Comment by bakura10** [comment]
But you should really wait for Doctrine 2.5 (it is due by early february), then we'll need to update DoctrineORMModule, and using ZfrCash will be possible :).

**Comment by finbarrmccarthy** [comment]
Thanks Michaël - Just testing at the moment, looking forward to this when its ready. Finbarr

**Comment by bakura10** [comment]
Hi @finbarrmccarthy ,

I have made a lot of progress, and I'm very happy with the architecture now. I have updated DoctrineORMModule to have the needed feature to support ZfrCash. I have also written the full documentation of ZfrCash: https://github.com/zf-fr/zfr-cash/blob/initial/README.md

You need Doctrine ORM 2.5, dev-master of DoctrineORMModule, and getting the branch "dev-initial" of ZfrCash. I will write the tests tomorrow, and then merge into master, and tag in a few days once it's tested in my app. But it should be pretty solid already!

Let me know if you need any help setting the module.

Please note however that I have simplified a bit its scope. I have given up the idea of automatically handling VAT (you'd better use a third party app like Quaderno or Octobat for that). It's more targetated at creating customers, creating/updating subscriptions, creating/updating discount, and keeping everything synchronized with Stripe.

**Comment by finbarrmccarthy** [comment]
Michaël, Thank you so much. This looks fantastic. I will implement tomorrow and report back.

**Comment by bakura10** [comment]
I've tag the beta 1, please get the new code, it contains ton of fix in the mapping.

I'm closing, if you have any issues, please open new issues ;).
