### ISSUE TITLE
Doctrine\DBAL\Schema\SchemaException

### ISSUE THREAD

**Issue by finbarrmccarthy** [zf-fr/zfr-cash#4]
When running 
**./vendor/bin/doctrine-module orm:validate-schema**
I get the following errors;
- [Mapping]  FAIL - The entity-class 'ZfrCash\Entity\SubscriptionDiscount' mapping is invalid:
- [Doctrine\DBAL\Schema\SchemaException]
  There is no column with name 'key' on table 'cash_plan_metadata'.

Is it correct to amend "ZfrCash.Entity.Subscription.dcm.xml"
**from** 
`<one-to-one field="discount" target-entity="ZfrCash\Entity\SubscriptionDiscount">`

**to** 
`<one-to-one field="discount" target-entity="ZfrCash\Entity\SubscriptionDiscount" inversed-by="subscription">`

AND CHANGE "ZfrCash.Entity.PlanMetadata.dcm.xml"

**from**
`<field name="key" column="`interval`" type="string" />`

**to** 
`<field name="key" column="`key`" type="string" />`

**Comment by bakura10** [comment]
Oops... I've fixed it and tagged the beta 3. Can you pull the latest version and try again ?

**Comment by bakura10** [comment]
Grrrr shit there are still errors. Please wait.

**Comment by bakura10** [comment]
I've updated the tag. v1.0.0-beta.3 should be fixed now.

**Comment by finbarrmccarthy** [comment]
Great, thanks. That seems fixed now.
